# Generated by Django 5.0.6 on 2024-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followed_blogs",
            field=models.JSONField(
                default=list,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="followed_podcasts",
            field=models.JSONField(
                default=list,
            ),
        ),
    ]
