# Generated by Django 5.0.6 on 2024-06-22 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_followed_blogs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followed_users",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
