# Generated by Django 5.0.6 on 2024-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_visit",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
